version: 2
jobs:
  build:
    working_directory: ~/side-navigation
    docker:
      - image: circleci/node:12.6.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - ./node_modules
      - run:
          name: Build Angular
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: Test Angular
          command: yarn test --watch=false --no-progress
      - store_artifacts:
          path: test-results/karma/results.xml
          prefix: tests
      - store_test_results:
          path: test-results
      - run:
          name: Running E2E tests
          command: yarn cytest
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

